//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace МагазинчикУДома
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int idCatigorie { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
